name: My Naughty script

on:
  workflow_dispatch:  # Enables manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Lambda
        env:
          CAT_API_KEY: ${{ secrets.CAT_API_KEY }}
          CAT_API_USER: ${{ vars.CAT_API_USER }}
        run: |
          echo ">>>>>>>>  Validate GitHub Actions masking <<<<<<<<"
          echo "$CAT_API_KEY"
          echo "$CAT_API_USER"
          echo ">>>>>>>>  NOM NOM NOM <<<<<<<<"
          echo "$CAT_API_KEY" | base64
          echo "$CAT_API_USER" | base64